"""PyInstaller entry point.

A console script's `lumen = lumen.cli:main` is generated by pip at install
time and does not exist in a frozen build, so the bundle needs a real module
to start from. It does nothing but call the same `main()`.

`multiprocessing.freeze_support()` is here because a frozen Windows binary
re-executes itself to spawn a child process; without it, any library that
reaches for multiprocessing would relaunch the whole app instead. Nothing in
Lumen does today, but tinytuya pulls in a broad dependency tree and the call
is a no-op in the parent, so it costs nothing to be safe.
"""

import multiprocessing
import sys

from lumen.cli import main

if __name__ == "__main__":
    multiprocessing.freeze_support()
    sys.exit(main())
